### ISSUE TITLE
update readme and publish new release

### ISSUE THREAD

**Issue by ctf0** [gocanto/vuemit#10]
the readme can be more straight forward using a table, i can make a PR if you are ok with that.

can we tag a new release with the newly added commits ?

https://github.com/gocanto/vuemit/pull/11

**Comment by gocanto** [comment]
It sounds good to me :)

**Comment by ctf0** [comment]
any news ?

**Comment by gocanto** [comment]
Will be doong this week buddy. I have moved and been bussy :)

**Comment by gocanto** [comment]
done brother

vuemit@1.0.4
