### ISSUE TITLE
missing )

### ISSUE THREAD

**Issue by massimoselvi** [gocanto/vuemit#14]
Vuemit.js file, line 114

I found it like this: 		this.vue.$off(event;

of course it must be:
this.vue.$off(event);

pls fix and update

**Comment by gocanto** [comment]
Would u like to send a PR? :)

**Comment by gocanto** [comment]
To be honest, I do not spot the error within ur example.

**Comment by ctf0** [comment]
already fixed in https://github.com/gocanto/vuemit/pull/13, we just need new release tag

**Comment by gocanto** [comment]
done 

https://github.com/gocanto/vuemit/commit/b2430bb209f561cd4ccc060e971d308f35b9f88f



thanks
