### ISSUE TITLE
npm run production: Unexpected token: name (Vuemit)

### ISSUE THREAD

**Issue by liamomagma** [gocanto/vuemit#17]
Running `npm run production` in current Laravel 5.5 gives the following errror.

```
@ ./resources/assets/js/app.js 59:35-72
@ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

error

/js/app.js from UglifyJs
Unexpected token: name (Vuemit) [./~/vuemit/src/Vuemit.js:11,0][/js/app.js:54904,6]
```

In my app.js I have `window.Vuemit = require('vuemit');` but fails with the above error.

**Comment by gocanto** [comment]
@ctf0 have you seen this error? I can not reproduce it

**Comment by ctf0** [comment]
https://github.com/gocanto/vuemit/issues/6
https://ctf0.wordpress.com/2017/09/12/laravel-mix-es6/

**Comment by gocanto** [comment]
Will check it later. Thanks :)

**Comment by ctf0** [comment]
@gocanto its not meant for u, anyway we should update the readme about installing the presets and enabling them in the webpack config.

**Comment by gocanto** [comment]
Yeah, we can do that @ctf0 

are you sending the PR, otherwise I will try to do it this coming weekend?

**Comment by ctf0** [comment]
for laravel just add a link to the article , but for node am not sure how the webpack config would be.
