### ISSUE TITLE
Vuemit.js:128 Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by cpuzzuol** [gocanto/vuemit#18]
Using Laravel (5.5) Homestead with the [Laravel Media Manager](https://github.com/ctf0/Laravel-Media-Manager)

This is called from the file [manager.js](https://github.com/ctf0/Laravel-Media-Manager/blob/master/src/resources/assets/js/manager.js)

The vuemit library is included on line 10 of the manager.js file:
window.EventHub = require('vuemit')

This causes the error in the title of this issue.

**Comment by gocanto** [comment]
This a bug on their end. I would like to help you out, but there is nothing I can do to solve this for you. Thanks for testing :)
