### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by eugeniregi** [gocanto/vuemit#19]
Hello
I get this error with nyc package when install vuemit with npm 5.6.0 
![captura de pantalla de 2018-02-16 07-04-18](https://user-images.githubusercontent.com/2988275/36295427-cbba2048-12e7-11e8-8612-cdea7610a52e.png)

I  hope you can help me
Thanks!

**Comment by gocanto** [comment]
I am not able to reproduce your issue. can u provide more info?

**Comment by gocanto** [comment]
Does this fix your issue?
https://github.com/gocanto/vuemit/pull/21

**Comment by gocanto** [comment]
there is a new release `1.0.9` 
does this fix it for you?
