### ISSUE TITLE
Uncaught ReferenceError: Vue is not defined

### ISSUE THREAD

**Issue by lmartins** [gocanto/vuemit#4]
Hi,

This is probably due to something with my config, but I was wondering if you have seen this issue before.

Im importing Vue to my app with 
```
import Vue from 'vue'
```
Also tried with:
```
let Vue = require('vue');
```
And all works well until I try to require `vuemit`. Then the app breaks with the following error:
```
Uncaught ReferenceError: Vue is not defined
```

Worth mentioning this is built using Webpack, where I have the following on my aliases:
```
    resolve: {
        alias: {
            'vue$': 'vue/dist/vue.common.js'
        }
    },
```
Any tips you could share?

**Comment by gocanto** [comment]
Well i am not realt familiar with webpak but that is due to your loaders. Let me try to find somethimg i can ise to help u out

**Comment by gocanto** [comment]
Ok, I think it might an issue from my side. Let me plat it with it and come back up to you. 

Let me know if you happen to find something. 

Thanks for testing!

**Comment by gocanto** [comment]
As I told you above, I am not familiar with webpack. I personally use Laravel Mix. You might take a look a its configuration file and loaders, so you might get an idea on how to set this up. 

Configuration file https://github.com/JeffreyWay/laravel-mix/blob/master/setup/webpack.config.js


Thanks for testing!

**Comment by jasperf** [comment]
Having the same issue @lmartins had before. How did you solve this?

Can convert `node_modules/vuemit/src/Vuemit.js` initial part to ES6 module

```js
....
import Vue from 'vue'

class Vuemit
{
    /**
	 * Creates a new Event instance.
	 *
	 * @return {Void}
	 */
    constructor()
...
```
and then import 
```
...
import EventHub from 'vuemit'
window.EventHub = EventHub
...
```

works , but then I still see no warning popup / modal.

**Comment by gocanto** [comment]
This pkg has been out maintenance for while. No sure if any of you wanna send a PR to fix the issue.
