### ISSUE TITLE
Production compile unexpected token: name

### ISSUE THREAD

**Issue by RaiserWeb** [gocanto/vuemit#6]
When I run 'npm run production' on my project, I am getting an error:

/backend/js/app.js from UglifyJs
Unexpected token: name (Vuemit) [./~/vuemit/src/Vuemit.js:9,0][/backend/js/app.js:55769,6]

I can't work out what the issue may be, but assuming something to do with webpack / babel compilation errors?

in package.json:

    "vuemit": "^1.0.3",
    "laravel-mix": "^0.10.0",

**Comment by gocanto** [comment]
Can I see the file where you are pulling in this pack?

**Comment by RaiserWeb** [comment]
Thanks for the reply. Pulling in this pack in my bootstrap.js file, 

window.Vuemit = require('vuemit');

I've since discovered the issue is not related to this package. It's an issue with Laravel mix (build tool) not transpiling the ES6 style package. I removed this package, and had exactly the same issue with another ES6 package.

For now I've manually transpilled this package, and included it that way. Thanks

**Comment by gocanto** [comment]
Excellent!

**Comment by ctf0** [comment]
@gocanto am having the same issue but slightly diff as once vueemit is removed the compiling works & here is the error
```bash
/assets/js/app.30a25b6acf3b0b2505e7.js from UglifyJs
Unexpected token: name (Vuemit) [./~/vuemit/src/Vuemit.js:9,0][/assets/js/app.30a25b6acf3b0b2505e7.js:428,6]
```

so is there anything i should add to the build process to fix this ?

**Comment by gocanto** [comment]
Hey @ctf0, 


Can I see your bootstrap file and invoke one?

**Comment by ctf0** [comment]
u can test with https://github.com/ctf0/Notification-Component

and for the `webpack.mix.js` 
```js
const { mix } = require('laravel-mix');

mix.js('resources/assets/js/app.js', 'public/assets/js').version();
```

if you need something else plz tell me

**Comment by gocanto** [comment]
I will check and send a pr if needed

**Comment by ctf0** [comment]
@gocanto any news over this ?

**Comment by RaiserWeb** [comment]
@ctf0 I used a transpiler tool to run the package script though, then created js files inside my project js folder and required them that way. I used this to transpile https://babeljs.io/repl

**Comment by ctf0** [comment]
@RaiserWeb thanx for the suggestion, but if this is the only solution for such issue, i believe the package should use that transpile or similar internally, 

the whole idea of package managers is you dont need to use external tools to finish the job, otherwise why use npm in the first place ?

**Comment by RaiserWeb** [comment]
@ctf0 Are you using Laravel-mix to compile? It appeared to me that mix was where the bug lied, not this package. I raised an issue at laravel-mix, but no joy yet. So in order to keep going on my project, I used the mentioned work around until things get sorted.

**Comment by ctf0** [comment]
okay thanx, for me am sticking to `dev` build for now until the problem is sorted.

can u add a reference to the ticket on laravel mix ?

**Comment by ctf0** [comment]
**update** 
to fix
```bash
yarn add --dev babel-preset-es2015 babel-preset-stage-2
```
- webpack.mix.js
```js
const res = 'resources/assets'
const pub = 'public/assets'

mix.webpackConfig({
    module: {
        rules: [
            {
                test: /\.jsx?$/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['env', 'es2015', 'stage-2']
                    }
                }
            }
        ]
    }
})

// App
mix.js(res + '/js/app.js', pub + '/js/app.js')
    .sass(res + '/sass/app.scss', pub + '/css')
    .version()
```
