### ISSUE TITLE
[feature] use a wildcard for events name

### ISSUE THREAD

**Issue by ctf0** [gocanto/vuemit#7]
i found https://github.com/vuejs/vue/issues/230#issuecomment-219911934, but not sure how to implement it with the `vuemeit`, however maybe we can have an internal check for something like 
```js
EventHub.listen('*', (data)=>{
    // do something
})
```

which essentially use regex to catch events name.

**Comment by gocanto** [comment]
This can be achieved using https://github.com/gocanto/vuemit/blob/master/src/Vuemit.js#L47

right?

**Comment by ctf0** [comment]
am sorry for not being explaining correctly what am after, ex.

```js
EventHub.fire('pub-foo', data)
EventHub.fire('pub-bar', data)

// now we want one listener for all events name of "pub-*"
EventHub.listen('pub-*', callback)
{
     // do something
}
```

however atm the listen method wont work because it needs an absolute name of the event not a pattern.

**Comment by gocanto** [comment]
Can you point me out to this option in the Vue js doc? I haven't been able to play with Vue for a while now. Been really busy! 

I might be able to pull this off :)

**Comment by ctf0** [comment]
actually its not in the docs, only where i could find this were https://github.com/vuejs/vue/issues/230#issuecomment-219911934

**Comment by gocanto** [comment]
Ok, let me take a look at it and see what I can do.

**Comment by gocanto** [comment]
Have you checked if this work properly? 

I am kinda busy at the moment and have not had time to check on this. 

If you find it useful and wanna PR for it, I will merge it.

**Comment by ctf0** [comment]
its okay np, will see what i can do 👍

**Comment by ctf0** [comment]
i think with the events name array, we dont need this one, as it will make it harder to test it and/or to reason about.
